# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BCalculator_ROE v2GLOVRH.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QFont)
from PySide6.QtWidgets import (QFrame, QLabel,
    QPushButton, QSizePolicy, QTextEdit)

class Ui_DialogROE(object):
    def setupUi(self, DialogROE):
        if not DialogROE.objectName():
            DialogROE.setObjectName(u"DialogROE")
        DialogROE.resize(399, 233)
        self.label = QLabel(DialogROE)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 40, 91, 16))
        self.ROEnetprofit = QTextEdit(DialogROE)
        self.ROEnetprofit.setObjectName(u"ROEnetprofit")
        self.ROEnetprofit.setGeometry(QRect(90, 40, 91, 21))
        self.ROEnetprofit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEnetprofit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEassets = QTextEdit(DialogROE)
        self.ROEassets.setObjectName(u"ROEassets")
        self.ROEassets.setGeometry(QRect(90, 70, 91, 21))
        self.ROEassets.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEassets.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_2 = QLabel(DialogROE)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 72, 81, 16))
        self.label_6 = QLabel(DialogROE)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(220, 72, 81, 16))
        self.ROEequity = QTextEdit(DialogROE)
        self.ROEequity.setObjectName(u"ROEequity")
        self.ROEequity.setGeometry(QRect(290, 70, 91, 21))
        self.ROEequity.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEequity.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.BtnROEok = QPushButton(DialogROE)
        self.BtnROEok.setObjectName(u"BtnROEok")
        self.BtnROEok.setGeometry(QRect(150, 200, 75, 24))
        self.BtnROEclear = QPushButton(DialogROE)
        self.BtnROEclear.setObjectName(u"BtnROEclear")
        self.BtnROEclear.setGeometry(QRect(230, 200, 75, 24))
        self.BtnROEclose = QPushButton(DialogROE)
        self.BtnROEclose.setObjectName(u"BtnROEclose")
        self.BtnROEclose.setGeometry(QRect(310, 200, 75, 24))
        self.label_13 = QLabel(DialogROE)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 40, 91, 16))
        self.ROErevenue = QTextEdit(DialogROE)
        self.ROErevenue.setObjectName(u"ROErevenue")
        self.ROErevenue.setGeometry(QRect(290, 40, 91, 21))
        self.ROErevenue.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROErevenue.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_3 = QLabel(DialogROE)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 150, 41, 16))
        self.label_4 = QLabel(DialogROE)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(140, 150, 71, 16))
        self.label_5 = QLabel(DialogROE)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(280, 150, 51, 16))
        self.label_7 = QLabel(DialogROE)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 120, 221, 16))
        font = QFont()
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.line = QFrame(DialogROE)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 100, 361, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(DialogROE)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 180, 361, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(DialogROE)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 10, 121, 16))
        self.label_8.setFont(font)
        self.ROEmargin = QTextEdit(DialogROE)
        self.ROEmargin.setObjectName(u"ROEmargin")
        self.ROEmargin.setGeometry(QRect(70, 150, 51, 21))
        self.ROEmargin.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEmargin.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEturnover = QTextEdit(DialogROE)
        self.ROEturnover.setObjectName(u"ROEturnover")
        self.ROEturnover.setGeometry(QRect(210, 150, 51, 21))
        self.ROEturnover.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROEturnover.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROElever = QTextEdit(DialogROE)
        self.ROElever.setObjectName(u"ROElever")
        self.ROElever.setGeometry(QRect(330, 150, 51, 21))
        self.ROElever.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ROElever.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        self.retranslateUi(DialogROE)

        QMetaObject.connectSlotsByName(DialogROE)
    # setupUi

    def retranslateUi(self, DialogROE):
        DialogROE.setWindowTitle(QCoreApplication.translate("DialogROE", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("DialogROE", u"\u51c0\u5229\u6da6\u989d:", None))
        self.label_2.setText(QCoreApplication.translate("DialogROE", u"\u603b\u8d44\u4ea7:", None))
        self.label_6.setText(QCoreApplication.translate("DialogROE", u"\u80a1\u4e1c\u6743\u76ca:", None))
        self.BtnROEok.setText(QCoreApplication.translate("DialogROE", u"\u786e\u8ba4", None))
        self.BtnROEclear.setText(QCoreApplication.translate("DialogROE", u"\u6e05\u7a7a", None))
        self.BtnROEclose.setText(QCoreApplication.translate("DialogROE", u"\u9000\u51fa", None))
        self.label_13.setText(QCoreApplication.translate("DialogROE", u"\u8425\u4e1a\u989d:", None))
        self.label_3.setText(QCoreApplication.translate("DialogROE", u"\u51c0\u5229\u7387:", None))
        self.label_4.setText(QCoreApplication.translate("DialogROE", u"\u8d44\u4ea7\u5468\u8f6c\u7387:", None))
        self.label_5.setText(QCoreApplication.translate("DialogROE", u"\u6760\u6746\u7387:", None))
        self.label_7.setText(QCoreApplication.translate("DialogROE", u"\u5173\u952e\u6bd4\u7387\u6d4b\u7b97\uff08\u4f18\u5148\u4e8e\u57fa\u7840\u6570\u636e\uff09:", None))
        self.label_8.setText(QCoreApplication.translate("DialogROE", u"\u57fa\u7840\u6570\u636e\u6d4b\u7b97:", None))
    # retranslateUi

