# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BCalculator_IRR v2HPRAuD.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtWidgets import (QLabel, QPushButton, QTextEdit)

class Ui_DialogIRR(object):
    def setupUi(self, DialogIRR):
        if not DialogIRR.objectName():
            DialogIRR.setObjectName(u"DialogIRR")
        DialogIRR.resize(399, 284)
        self.label = QLabel(DialogIRR)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 91, 16))
        self.IRRyear0invest = QTextEdit(DialogIRR)
        self.IRRyear0invest.setObjectName(u"IRRyear0invest")
        self.IRRyear0invest.setGeometry(QRect(120, 20, 131, 21))
        self.IRRyear0invest.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear0invest.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear1r = QTextEdit(DialogIRR)
        self.IRRyear1r.setObjectName(u"IRRyear1r")
        self.IRRyear1r.setGeometry(QRect(90, 60, 91, 21))
        self.IRRyear1r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear1r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_2 = QLabel(DialogIRR)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 62, 81, 16))
        self.label_3 = QLabel(DialogIRR)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 91, 81, 16))
        self.IRRyear3r = QTextEdit(DialogIRR)
        self.IRRyear3r.setObjectName(u"IRRyear3r")
        self.IRRyear3r.setGeometry(QRect(90, 90, 91, 21))
        self.IRRyear3r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear3r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_4 = QLabel(DialogIRR)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 122, 81, 16))
        self.IRRyear5r = QTextEdit(DialogIRR)
        self.IRRyear5r.setObjectName(u"IRRyear5r")
        self.IRRyear5r.setGeometry(QRect(90, 120, 91, 21))
        self.IRRyear5r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear5r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_5 = QLabel(DialogIRR)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 152, 81, 16))
        self.IRRyear7r = QTextEdit(DialogIRR)
        self.IRRyear7r.setObjectName(u"IRRyear7r")
        self.IRRyear7r.setGeometry(QRect(90, 150, 91, 21))
        self.IRRyear7r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear7r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_6 = QLabel(DialogIRR)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(220, 62, 81, 16))
        self.IRRyear2r = QTextEdit(DialogIRR)
        self.IRRyear2r.setObjectName(u"IRRyear2r")
        self.IRRyear2r.setGeometry(QRect(290, 60, 91, 21))
        self.IRRyear2r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear2r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_7 = QLabel(DialogIRR)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 91, 81, 16))
        self.IRRyear4r = QTextEdit(DialogIRR)
        self.IRRyear4r.setObjectName(u"IRRyear4r")
        self.IRRyear4r.setGeometry(QRect(290, 90, 91, 21))
        self.IRRyear4r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear4r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_8 = QLabel(DialogIRR)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(220, 122, 81, 16))
        self.IRRyear6r = QTextEdit(DialogIRR)
        self.IRRyear6r.setObjectName(u"IRRyear6r")
        self.IRRyear6r.setGeometry(QRect(290, 120, 91, 21))
        self.IRRyear6r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear6r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear8r = QTextEdit(DialogIRR)
        self.IRRyear8r.setObjectName(u"IRRyear8r")
        self.IRRyear8r.setGeometry(QRect(290, 150, 91, 21))
        self.IRRyear8r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear8r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_9 = QLabel(DialogIRR)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 152, 81, 16))
        self.IRRyear10r = QTextEdit(DialogIRR)
        self.IRRyear10r.setObjectName(u"IRRyear10r")
        self.IRRyear10r.setGeometry(QRect(290, 178, 91, 21))
        self.IRRyear10r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear10r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear9r = QTextEdit(DialogIRR)
        self.IRRyear9r.setObjectName(u"IRRyear9r")
        self.IRRyear9r.setGeometry(QRect(90, 178, 91, 21))
        self.IRRyear9r.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyear9r.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_10 = QLabel(DialogIRR)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 180, 81, 16))
        self.label_11 = QLabel(DialogIRR)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(220, 180, 81, 16))
        self.IRRyearfr = QTextEdit(DialogIRR)
        self.IRRyearfr.setObjectName(u"IRRyearfr")
        self.IRRyearfr.setGeometry(QRect(190, 210, 191, 21))
        self.IRRyearfr.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.IRRyearfr.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.label_12 = QLabel(DialogIRR)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 210, 161, 16))
        self.BtnIRRok = QPushButton(DialogIRR)
        self.BtnIRRok.setObjectName(u"BtnIRRok")
        self.BtnIRRok.setGeometry(QRect(146, 244, 75, 24))
        self.BtnIRRclear = QPushButton(DialogIRR)
        self.BtnIRRclear.setObjectName(u"BtnIRRclear")
        self.BtnIRRclear.setGeometry(QRect(226, 244, 75, 24))
        self.BtnIRRclose = QPushButton(DialogIRR)
        self.BtnIRRclose.setObjectName(u"BtnIRRclose")
        self.BtnIRRclose.setGeometry(QRect(306, 244, 75, 24))

        self.retranslateUi(DialogIRR)

        QMetaObject.connectSlotsByName(DialogIRR)
    # setupUi

    def retranslateUi(self, DialogIRR):
        DialogIRR.setWindowTitle(QCoreApplication.translate("DialogIRR", u"Dialog", None))
        self.label.setText(QCoreApplication.translate("DialogIRR", u"\u521d\u59cb\u6295\u8d44(\u6b63\u6570)\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e00\u5e74\u6536\u76ca\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e09\u5e74\u6536\u76ca\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e94\u5e74\u6536\u76ca\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e03\u5e74\u6536\u76ca\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e8c\u5e74\u6536\u76ca\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u56db\u5e74\u6536\u76ca\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u516d\u5e74\u6536\u76ca\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u516b\u5e74\u6536\u76ca\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u4e5d\u5e74\u6536\u76ca\uff1a", None))
        self.label_11.setText(QCoreApplication.translate("DialogIRR", u"\u7b2c\u5341\u5e74\u6536\u76ca\uff1a", None))
        self.label_12.setText(QCoreApplication.translate("DialogIRR", u"\u540e\u7eed\u6536\u76ca\uff08\u4ee5\u82f1\u6587\u9017\u53f7\u5206\u9694\uff09\uff1a", None))
        self.BtnIRRok.setText(QCoreApplication.translate("DialogIRR", u"\u786e\u8ba4", None))
        self.BtnIRRclear.setText(QCoreApplication.translate("DialogIRR", u"\u6e05\u7a7a", None))
        self.BtnIRRclose.setText(QCoreApplication.translate("DialogIRR", u"\u9000\u51fa", None))
    # retranslateUi

